################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
LINKER_SCRIPT := 
SX_SRCS := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
X_UPPER_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CREF := 
SRC_DEPS := 
OBJCOPY := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
OBJS := 
SX_UPPER_DEPS := 
ASM_DEPS := 
MAP := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
mtk3_bsp2/.git \
mtk3_bsp2/.git/info \
mtk3_bsp2/.git/logs \
mtk3_bsp2/.git/logs/refs/heads \
mtk3_bsp2/.git/logs/refs/remotes/origin \
mtk3_bsp2/.git/modules/mtkernel \
mtk3_bsp2/.git/modules/mtkernel/info \
mtk3_bsp2/.git/modules/mtkernel/logs \
mtk3_bsp2/.git/modules/mtkernel/logs/refs/heads \
mtk3_bsp2/.git/modules/mtkernel/logs/refs/remotes/origin \
mtk3_bsp2/.git/modules/mtkernel/refs/heads \
mtk3_bsp2/.git/modules/mtkernel/refs/remotes/origin \
mtk3_bsp2/.git/refs/heads \
mtk3_bsp2/.git/refs/remotes/origin \
mtk3_bsp2/etc/linker \
mtk3_bsp2/mtkernel/build_make \
mtk3_bsp2/mtkernel/device/adc \
mtk3_bsp2/mtkernel/device/common/drvif \
mtk3_bsp2/mtkernel/device/i2c \
mtk3_bsp2/mtkernel/device/ser \
mtk3_bsp2/mtkernel/kernel/inittask \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/kernel/sysinit \
mtk3_bsp2/mtkernel/kernel/tkernel \
mtk3_bsp2/mtkernel/kernel/tstdlib \
mtk3_bsp2/mtkernel/kernel/usermain \
mtk3_bsp2/mtkernel/lib/libtk \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/lib/libtm \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/no_device \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_adc \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_adhb \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i3c_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_sci_i2c \
mtk3_bsp2/sysdepend/ra_fsp \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8p1 \
ra/arm/CMSIS-DSP/Source/BasicMathFunctions \
ra/arm/CMSIS-DSP/Source/BayesFunctions \
ra/arm/CMSIS-DSP/Source/CommonTables \
ra/arm/CMSIS-DSP/Source/ComplexMathFunctions \
ra/arm/CMSIS-DSP/Source/ControllerFunctions \
ra/arm/CMSIS-DSP/Source/DistanceFunctions \
ra/arm/CMSIS-DSP/Source/FastMathFunctions \
ra/arm/CMSIS-DSP/Source/FilteringFunctions \
ra/arm/CMSIS-DSP/Source/InterpolationFunctions \
ra/arm/CMSIS-DSP/Source \
ra/arm/CMSIS-DSP/Source/MatrixFunctions \
ra/arm/CMSIS-DSP/Source/QuaternionMathFunctions \
ra/arm/CMSIS-DSP/Source/SVMFunctions \
ra/arm/CMSIS-DSP/Source/StatisticsFunctions \
ra/arm/CMSIS-DSP/Source/SupportFunctions \
ra/arm/CMSIS-DSP/Source/TransformFunctions \
ra/arm/CMSIS-DSP/Source/WindowFunctions \
ra/arm/CMSIS-NN/Source/ActivationFunctions \
ra/arm/CMSIS-NN/Source/BasicMathFunctions \
ra/arm/CMSIS-NN/Source/ConcatenationFunctions \
ra/arm/CMSIS-NN/Source/ConvolutionFunctions \
ra/arm/CMSIS-NN/Source/FullyConnectedFunctions \
ra/arm/CMSIS-NN/Source/LSTMFunctions \
ra/arm/CMSIS-NN/Source/NNSupportFunctions \
ra/arm/CMSIS-NN/Source/PadFunctions \
ra/arm/CMSIS-NN/Source/PoolingFunctions \
ra/arm/CMSIS-NN/Source/ReshapeFunctions \
ra/arm/CMSIS-NN/Source/SVDFunctions \
ra/arm/CMSIS-NN/Source/SoftmaxFunctions \
ra/arm/CMSIS-NN/Source/TransposeFunctions \
ra/arm/CMSIS-View/EventRecorder/Source \
ra/arm/CMSIS_6 \
ra/board/ra8p1_ek \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra8p1 \
ra/fsp/src/r_dmac \
ra/fsp/src/r_drw \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_mipi_csi \
ra/fsp/src/r_mipi_phy \
ra/fsp/src/r_ospi_b \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/r_vin \
ra/fsp/src/rm_ethosu \
ra/npu/ethos-u-core-driver/src \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/core/api \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/core/c \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/kernels/internal \
ra/npu/tflite-micro/tensorflow/compiler/mlir/lite/schema \
ra/npu/tflite-micro/tensorflow/lite/c \
ra/npu/tflite-micro/tensorflow/lite/core \
ra/npu/tflite-micro/tensorflow/lite/core/api \
ra/npu/tflite-micro/tensorflow/lite/core/c \
ra/npu/tflite-micro/tensorflow/lite/kernels \
ra/npu/tflite-micro/tensorflow/lite/kernels/internal \
ra/npu/tflite-micro/tensorflow/lite/micro/tflite_bridge \
ra/npu/tflite-micro/tensorflow/lite/schema \
ra/tes/dave2d/src \
ra_gen \
src/SEGGER_RTT \
src/ai_app \
src/camera_layer \
src/common \
src/console_output \
src/display_layer \
src/display_layer/user_font_body \
src/display_layer/user_font_body/lc \
src/display_layer/user_font_body/uc \
src/esp32 \
src/external_memory \
src \
src/i2c_support \
src/time_counter \
src/touch \

