/*
 * ESP32 UART Driver & Telemetry Interface for Renesas EK-RA8P1
 * Pinout on Pmod 2: SCI0 (P602 RXD0, P603 TXD0)
 * OS: microT-Kernel 3.0 (TRON RTOS)
 */

#include "esp32_uart.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "../SEGGER_RTT/SEGGER_RTT.h"
#include "r_sci_b_uart.h"

/* FSP UART instance generated by e2 studio */
extern const uart_instance_t g_esp32_uart;

/* Global Telemetry Data */
esp32_telemetry_t g_esp32_data = {
    .last_message = "Waiting for ESP32...",
    .rx_bytes_total = 0,
    .rx_packets_total = 0,
    .error_count = 0,
    .is_connected = false,
    .has_new_msg = false,
    .last_rx_tick = 0,
    .co2 = 0,
    .temperature = 0.0f,
    .humidity = 0.0f,
    .accel_x = 0.0f,
    .accel_y = 0.0f,
    .accel_z = 0.0f,
    .gyro_x = 0.0f,
    .gyro_y = 0.0f,
    .gyro_z = 0.0f,
    .custom_val = 0,
    .status_str = "STANDBY"
};

/* Reception assembly buffer */
static char s_rx_buf[ESP32_MAX_MSG_LEN];
static volatile uint16_t s_rx_idx = 0;

/* Persistent TX buffer and completion flag */
static char s_tx_buf[ESP32_MAX_MSG_LEN + 32];
static volatile bool s_tx_complete = true;

void esp32_uart_callback(uart_callback_args_t *p_args)
{
    if (UART_EVENT_TX_COMPLETE == p_args->event || UART_EVENT_TX_DATA_EMPTY == p_args->event)
    {
        s_tx_complete = true;
    }
    else if (UART_EVENT_RX_CHAR == p_args->event)
    {
        g_esp32_data.rx_bytes_total++;
        uint8_t ch = (uint8_t)(p_args->data);

        if ('\r' == ch || '\n' == ch)
        {
            if (s_rx_idx > 0)
            {
                s_rx_buf[s_rx_idx] = '\0';
                strncpy(g_esp32_data.last_message, s_rx_buf, sizeof(g_esp32_data.last_message) - 1);
                g_esp32_data.last_message[sizeof(g_esp32_data.last_message) - 1] = '\0';
                g_esp32_data.rx_packets_total++;
                g_esp32_data.is_connected = true;
                g_esp32_data.has_new_msg = true;
                s_rx_idx = 0;
            }
        }
        else
        {
            if (s_rx_idx < (sizeof(s_rx_buf) - 1))
            {
                s_rx_buf[s_rx_idx++] = (char)ch;
            }
            else
            {
                /* Buffer full: null terminate and commit */
                s_rx_buf[s_rx_idx] = '\0';
                strncpy(g_esp32_data.last_message, s_rx_buf, sizeof(g_esp32_data.last_message) - 1);
                g_esp32_data.last_message[sizeof(g_esp32_data.last_message) - 1] = '\0';
                g_esp32_data.rx_packets_total++;
                g_esp32_data.is_connected = true;
                g_esp32_data.has_new_msg = true;
                s_rx_idx = 0;
            }
        }
    }
    else
    {
        g_esp32_data.error_count++;
    }
}

/* Backward compatibility alias */
void gps_uart_callback(uart_callback_args_t *p_args) __attribute__((weak, alias("esp32_uart_callback")));

/**
 * @brief Parse key-value pairs from telemetry string
 */
static void parse_telemetry_fields(const char *msg)
{
    /* 1. SCD40 CO2 concentration in ppm */
    char *co2_ptr = strstr(msg, "CO2");
    if (co2_ptr)
    {
        while (*co2_ptr && *co2_ptr != ':' && *co2_ptr != '=') co2_ptr++;
        if (*co2_ptr) g_esp32_data.co2 = (uint16_t)strtoul(co2_ptr + 1, NULL, 10);
    }

    /* 2. SCD40 Temperature in deg C */
    char *temp_ptr = strstr(msg, "TEMP");
    if (temp_ptr)
    {
        while (*temp_ptr && *temp_ptr != ':' && *temp_ptr != '=') temp_ptr++;
        if (*temp_ptr) g_esp32_data.temperature = (float)strtod(temp_ptr + 1, NULL);
    }

    /* 3. SCD40 Relative Humidity % */
    char *hum_ptr = strstr(msg, "HUM");
    if (hum_ptr)
    {
        while (*hum_ptr && *hum_ptr != ':' && *hum_ptr != '=') hum_ptr++;
        if (*hum_ptr) g_esp32_data.humidity = (float)strtod(hum_ptr + 1, NULL);
    }

    /* 4. MPU9250 Accelerometer X, Y, Z in g */
    char *ax_ptr = strstr(msg, "AX");
    if (ax_ptr)
    {
        while (*ax_ptr && *ax_ptr != ':' && *ax_ptr != '=') ax_ptr++;
        if (*ax_ptr) g_esp32_data.accel_x = (float)strtod(ax_ptr + 1, NULL);
    }

    char *ay_ptr = strstr(msg, "AY");
    if (ay_ptr)
    {
        while (*ay_ptr && *ay_ptr != ':' && *ay_ptr != '=') ay_ptr++;
        if (*ay_ptr) g_esp32_data.accel_y = (float)strtod(ay_ptr + 1, NULL);
    }

    char *az_ptr = strstr(msg, "AZ");
    if (az_ptr)
    {
        while (*az_ptr && *az_ptr != ':' && *az_ptr != '=') az_ptr++;
        if (*az_ptr) g_esp32_data.accel_z = (float)strtod(az_ptr + 1, NULL);
    }

    /* 5. MPU9250 Gyroscope X, Y, Z in deg/s */
    char *gx_ptr = strstr(msg, "GX");
    if (gx_ptr)
    {
        while (*gx_ptr && *gx_ptr != ':' && *gx_ptr != '=') gx_ptr++;
        if (*gx_ptr) g_esp32_data.gyro_x = (float)strtod(gx_ptr + 1, NULL);
    }

    char *gy_ptr = strstr(msg, "GY");
    if (gy_ptr)
    {
        while (*gy_ptr && *gy_ptr != ':' && *gy_ptr != '=') gy_ptr++;
        if (*gy_ptr) g_esp32_data.gyro_y = (float)strtod(gy_ptr + 1, NULL);
    }

    char *gz_ptr = strstr(msg, "GZ");
    if (gz_ptr)
    {
        while (*gz_ptr && *gz_ptr != ':' && *gz_ptr != '=') gz_ptr++;
        if (*gz_ptr) g_esp32_data.gyro_z = (float)strtod(gz_ptr + 1, NULL);
    }

    /* 6. Custom numerical value */
    char *val_ptr = strstr(msg, "VAL");
    if (val_ptr)
    {
        while (*val_ptr && *val_ptr != ':' && *val_ptr != '=') val_ptr++;
        if (*val_ptr) g_esp32_data.custom_val = (int32_t)strtol(val_ptr + 1, NULL, 10);
    }

    /* 7. Status string */
    char *stat_ptr = strstr(msg, "STATUS");
    if (stat_ptr)
    {
        while (*stat_ptr && *stat_ptr != ':' && *stat_ptr != '=') stat_ptr++;
        if (*stat_ptr)
        {
            stat_ptr++;
            size_t i = 0;
            while (stat_ptr[i] && stat_ptr[i] != ',' && stat_ptr[i] != ' ' && stat_ptr[i] != '\r' && stat_ptr[i] != '\n' && i < 31)
            {
                g_esp32_data.status_str[i] = stat_ptr[i];
                i++;
            }
            g_esp32_data.status_str[i] = '\0';
        }
    }
}

/**
 * @brief Initialize SCI0 for ESP32 UART communication
 */
fsp_err_t esp32_uart_init(uint32_t baudrate)
{
    FSP_PARAMETER_NOT_USED(baudrate);

    fsp_err_t err = g_esp32_uart.p_api->open(g_esp32_uart.p_ctrl, g_esp32_uart.p_cfg);
    if (FSP_SUCCESS != err && FSP_ERR_ALREADY_OPEN != err)
    {
        SEGGER_RTT_printf(0, "[ESP32] UART Open failed (%d)\r\n", err);
        return err;
    }

    SEGGER_RTT_printf(0, "[ESP32] UART ready on Pmod 2 (SCI0: P602 RX / P603 TX @ 115200 baud)\r\n");
    return FSP_SUCCESS;
}

/**
 * @brief Transmit string to ESP32 / PC Serial Monitor
 */
fsp_err_t esp32_uart_send(const char *p_str)
{
    if (NULL == p_str) return FSP_ERR_INVALID_POINTER;
    uint32_t len = (uint32_t)strlen(p_str);
    if (0 == len) return FSP_SUCCESS;

    /* Wait for previous transmission to finish */
    uint32_t timeout = 200000;
    while (!s_tx_complete && --timeout)
    {
        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MICROSECONDS);
    }

    if (len >= sizeof(s_tx_buf)) len = sizeof(s_tx_buf) - 1;
    memcpy(s_tx_buf, p_str, len);
    s_tx_buf[len] = '\0';
    s_tx_complete = false;

    fsp_err_t err = g_esp32_uart.p_api->write(g_esp32_uart.p_ctrl, (uint8_t const *)s_tx_buf, len);
    if (FSP_SUCCESS != err)
    {
        s_tx_complete = true;
        return err;
    }

    /* Wait for completion to guarantee full transmission */
    timeout = 200000;
    while (!s_tx_complete && --timeout)
    {
        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MICROSECONDS);
    }

    return FSP_SUCCESS;
}

fsp_err_t esp32_uart_write(const uint8_t *p_data, uint32_t length)
{
    if (NULL == p_data || 0 == length) return FSP_ERR_INVALID_POINTER;
    return g_esp32_uart.p_api->write(g_esp32_uart.p_ctrl, p_data, length);
}

/**
 * @brief Process buffered bytes from UART
 */
uint32_t esp32_uart_process(void)
{
    sci_b_uart_instance_ctrl_t *p_ctrl = (sci_b_uart_instance_ctrl_t *)g_esp32_uart.p_ctrl;

    /* 1. Clear any hardware receiver error flags to prevent lockup */
    if (p_ctrl && p_ctrl->p_reg)
    {
        uint32_t err_mask = (R_SCI_B0_CSR_ORER_Msk | R_SCI_B0_CSR_FER_Msk | R_SCI_B0_CSR_PER_Msk);
        if (p_ctrl->p_reg->CSR & err_mask)
        {
            g_esp32_data.error_count++;
            p_ctrl->p_reg->CFCLR |= err_mask;
        }
    }

    /* 2. Check if a complete message was received in callback */
    if (g_esp32_data.has_new_msg)
    {
        parse_telemetry_fields(g_esp32_data.last_message);

        /* Echo message back to ESP32 / PC Serial Monitor */
        static char s_echo_buf[ESP32_MAX_MSG_LEN + 32];
        snprintf(s_echo_buf, sizeof(s_echo_buf), "RA8P1 RX: %s\r\n", g_esp32_data.last_message);
        esp32_uart_send(s_echo_buf);

        SEGGER_RTT_printf(0, "[ESP32 MSG -> LCD]: %s\r\n", g_esp32_data.last_message);
        return 1;
    }

    return 0;
}

void esp32_uart_log_regs(void)
{
    sci_b_uart_instance_ctrl_t *p_ctrl = (sci_b_uart_instance_ctrl_t *)g_esp32_uart.p_ctrl;
    if (p_ctrl && p_ctrl->p_reg)
    {
        SEGGER_RTT_printf(0, "[SCI0 REGS] CSR=0x%08X CCR0=0x%08X FCR=0x%08X\r\n",
                          (unsigned int)p_ctrl->p_reg->CSR,
                          (unsigned int)p_ctrl->p_reg->CCR0,
                          (unsigned int)p_ctrl->p_reg->FCR);
    }
}

void esp32_fetch_sensor_data(void)
{
    esp32_uart_send("REQ\r\n");
}

void esp32_pin_scope(void)
{
    /* No-op */
}
